### ISSUE TITLE
Error entering website

### ISSUE THREAD

**Issue by andrixnet** [flopp/FloppsMap#81]
![flopp](https://user-images.githubusercontent.com/3382777/35039859-ceb372a8-fb87-11e7-901f-b786d5486586.png)

I was following this link https://flopp-caching.de/ from www.opencaching.ro

**Comment by flopp** [comment]
Thank you for reporting this issue.

There are actually two problems:
1. Your browser didn't reload the current translation files; that's why you get an error dialog with template strings (=> that's hopefully fixed by now)
2. The location detection by WiFi doesn't work on default installations of Firefox. I will write a short help text on how to configure Firefox properly.

**Comment by andrixnet** [comment]
Well, I was using desktop computer with cable network. No WiFi involved. In this case, detection by WiFi is invalid by default.
If what you meant was location by IP, then that component might have issues. 

Second, it shouldn't require a visiting user to make specific configurations in their browser to visit a website. 

Third, on this same FF instance, when visiting some website, I do get asked by a dialog if I want to share location information with that website. So then again I think there might be some issues with the location detection code of the Flopp's Map website.
